---
resources:
  - name: eureka-server-repo
    type: git
    source:
      uri: https://github.com/metflix/eureka-server
      branch: master
  - name: cf
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space}}
      skip_cert_check: true
  - name: cf-dev
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-org}}
      space: {{cf-space-dev}}
      skip_cert_check: true
  - name: m2
    type: docker-image
    source:
      repository: {{docker-repo}}

jobs:
  - name: eureka-server-unit
    serial: true
    plan:
      - get: eureka-server-repo
        trigger: true
      - get: m2
      - task: unit
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine
          inputs:
            - name: eureka-server-repo
              path: repo
            - name: m2
          run:
            path: sh
            args:
            - repo/ci/tasks/unit.sh
  - name: eureka-server-deploy-dev
    plan:
      - get: eureka-server-repo
        trigger: true
        passed: [ eureka-server-unit ]
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine
          inputs:
            - name: eureka-server-repo
              path: repo
            - name: m2
          outputs:
            - name: output
          run:
            path: sh
            args:
            - repo/ci/tasks/package.sh
      - put: cf-dev
        params:
          manifest: eureka-server-repo/manifest-dev.yml
          path: output/app.jar
          current_app_name: eureka-server-metflix-dev
  - name: eureka-server-deploy
    plan:
      - get: eureka-server-repo
        trigger: true
        passed: [ eureka-server-unit ]
      - get: m2
      - task: package
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: java
              tag: 8-jdk-alpine
          inputs:
            - name: eureka-server-repo
              path: repo
            - name: m2
          outputs:
            - name: output
          run:
            path: sh
            args:
            - repo/ci/tasks/package.sh
      - put: cf
        params:
          manifest: eureka-server-repo/manifest.yml
          path: output/app.jar
          current_app_name: eureka-server-metflix

  - name: eureka-server-create-service
    plan:
      - task: create-service
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
          run:
            path: sh
            args:
            - -c
            - |
              cf login -a {{cf-api}} -u {{cf-username}} -p {{cf-password}} -o {{cf-org}} -s {{cf-space}}
              cf create-user-provided-service eureka-server -p '{"uri":"http://eureka-server-metflix.cfapps.io"}'

  - name: eureka-server-create-service-dev
    plan:
      - task: create-service
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/cf-cli
          run:
            path: sh
            args:
            - -c
            - |
              cf login -a {{cf-api}} -u {{cf-username}} -p {{cf-password}} -o {{cf-org}} -s {{cf-space-dev}}
              cf create-user-provided-service eureka-server -p '{"uri":"http://eureka-server-dev-metflix.cfapps.io"}'